- name: Deploy Flask App
  hosts: web
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: latest

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker Image
      command: |
        docker pull joolsv/flask-app:latest

    - name: Run Docker Container
      command: |
        docker run -d -p 5000:5000 --name flask-app joolsv/flask-app:latest
