- name: Deploy Flask App
  hosts: web
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Start Docker Service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Log in to DockerHub
      ansible.builtin.command: docker login -u {{ lookup('env', 'DOCKERHUB_USERNAME') }} -p {{ lookup('env', 'DOCKERHUB_PASSWORD') }}

    - name: Pull Docker Image
      ansible.builtin.command: docker pull {{ lookup('env', 'DOCKERHUB_USERNAME') }}/flask-app:latest
      changed_when: false

    - name: Run Docker Container
      ansible.builtin.command: docker run -d -p 5000:5000 --name flask-app {{ lookup('env', 'DOCKERHUB_USERNAME') }}/flask-app:latest
      changed_when: false
