version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

  docker-executor:
    docker:
      - image: cimg/base:stable

  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.8.1

  ansible-executor:
    docker:
      - image: geerlingguy/docker-ubuntu2004-ansible:latest

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest

  build-docker-image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USERNAME/flask-app:latest .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/flask-app:latest

  deploy-terraform:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Apply Terraform
          command: terraform apply -auto-approve

  deploy-ansible:
    executor: ansible-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "$SSH_KEY_FINGERPRINT"
      - run:
          name: Install SSH
          command: apt-get update && apt-get install -y openssh-client
      - run:
          name: Setup SSH and Known Hosts
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            ssh-keyscan -H $EC2_PUBLIC_IP 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: Generate Inventory File
          command: |
            echo "[web]" > inventory.ini
            echo "ec2-instance ansible_host=$EC2_PUBLIC_IP ansible_user=ec2-user ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini
      - run:
          name: Verify SSH Connection
          command: ssh -vvv -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP "echo 'SSH is working'"
      - run:
          name: Verify Ansible
          command: ansible --version
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook -i inventory.ini deploy.yml

workflows:
  version: 2
  deploy-app:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
      - deploy-terraform:
          requires:
            - build-docker-image
      - deploy-ansible:
          requires:
            - deploy-terraform
