version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.5.7
    working_directory: ~/project

  ansible-executor:
    docker:
      - image: geerlingguy/docker-ubuntu2004-ansible:latest
    working_directory: ~/project

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest

  build-docker-image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USERNAME/flask-app:latest .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/flask-app:latest

  deploy-terraform:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            terraform init
      - run:
          name: Apply Terraform
          command: |
            terraform apply -auto-approve

  deploy-ansible:
    executor: ansible-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI, Curl & SSM Plugin
          command: |
            apt update -y
            apt install -y awscli curl python3-pip
            curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
            dpkg -i session-manager-plugin.deb
            session-manager-plugin --version
      - run:
          name: Install Python Packages (`boto3`, `botocore`, `ansible`)
          command: |
            pip3 install --upgrade pip
            pip3 install boto3 botocore ansible
      - run:
          name: Run Ansible Playbook via AWS SSM
          command: |
            aws ssm send-command \
              --document-name "AWS-RunShellScript" \
              --targets Key=instanceIds,Values=i-0175556a936e573ec \
              --parameters "commands=['ansible-playbook -i inventory.ini deploy.yml']" \
              --region us-east-1
      - run:
          name: Check Ansible Execution Status
          command: |
            aws ssm list-command-invocations --region us-east-1

workflows:
  version: 2
  deploy-app:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
      - deploy-terraform:
          requires:
            - build-docker-image
      - deploy-ansible:
          requires:
            - deploy-terraform
